/*flexberryautogenerated="true"*/
namespace IIS.PMZ
{
    using System;
    using ICSSoft.STORMNET.Web.Controls;

    using Resources;

    public partial class КонтрагентL : BaseListForm<Контрагент>
    {
        /// <summary>
        /// Конструктор без параметров,
        /// инициализирует свойства, соответствующие конкретной форме.
        /// </summary>
        public КонтрагентL() : base(Контрагент.Views.КонтрагентL)
        {
            EditPage = КонтрагентE.FormPath;
        }
                
        /// <summary>
        /// Путь до формы.
        /// </summary>
        public static string FormPath
        {
            get { return "~/forms/Kontragent/KontragentL.aspx"; }
        }

        /// <summary>
        /// Вызывается самым первым в Page_Load.
        /// </summary>
        protected override void Preload()
        {
        }

        /// <summary>
        /// Вызывается самым последним в Page_Load.
        /// </summary>
        protected override void Postload()
        {
        }
    }
}
