//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.PMZ
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// T вид закупки.
    /// </summary>
    // *** Start programmer edit section *** (tВидЗакупки CustomAttributes)

    // *** End programmer edit section *** (tВидЗакупки CustomAttributes)
    public enum tВидЗакупки
    {
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tВидЗакупки.Разовая CustomAttributes)

        // *** End programmer edit section *** (tВидЗакупки.Разовая CustomAttributes)
        Разовая,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tВидЗакупки.Запланированная CustomAttributes)

        // *** End programmer edit section *** (tВидЗакупки.Запланированная CustomAttributes)
        Запланированная,
    }
}
