//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.PMZ
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// T условия поставки и оплаты.
    /// </summary>
    // *** Start programmer edit section *** (tУсловияПоставкиИОплаты CustomAttributes)

    // *** End programmer edit section *** (tУсловияПоставкиИОплаты CustomAttributes)
    public enum tУсловияПоставкиИОплаты
    {
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tУсловияПоставкиИОплаты.Условие1 CustomAttributes)

        // *** End programmer edit section *** (tУсловияПоставкиИОплаты.Условие1 CustomAttributes)
        Условие1,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tУсловияПоставкиИОплаты.Условие2 CustomAttributes)

        // *** End programmer edit section *** (tУсловияПоставкиИОплаты.Условие2 CustomAttributes)
        Условие2,
    }
}
