//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.PMZ
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Договор.
    /// </summary>
    // *** Start programmer edit section *** (Договор CustomAttributes)

    // *** End programmer edit section *** (Договор CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДоговорE", new string[] {
            "Номер as \'Номер\'",
            "ЗакупкаТМЦ as \'Закупка ТМЦ\'",
            "ЗакупкаТМЦ.СтартоваяЦена as \'Стартовая цена\'"})]
    [AssociatedDetailViewAttribute("ДоговорE", "Платёж", "ПлатёжE", true, "", "Платёж", true, new string[] {
            ""})]
    [View("ДоговорL", new string[] {
            "Номер as \'Номер\'",
            "ЗакупкаТМЦ.СтартоваяЦена as \'Стартовая цена\'"})]
    public class Договор : ICSSoft.STORMNET.DataObject
    {
        
        private string fНомер;
        
        private IIS.PMZ.ЗакупкаТМЦ fЗакупкаТМЦ;
        
        private IIS.PMZ.DetailArrayOfПлатёж fПлатёж;
        
        // *** Start programmer edit section *** (Договор CustomMembers)

        // *** End programmer edit section *** (Договор CustomMembers)

        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (Договор.Номер CustomAttributes)

        // *** End programmer edit section *** (Договор.Номер CustomAttributes)
        [StrLen(255)]
        public virtual string Номер
        {
            get
            {
                // *** Start programmer edit section *** (Договор.Номер Get start)

                // *** End programmer edit section *** (Договор.Номер Get start)
                string result = this.fНомер;
                // *** Start programmer edit section *** (Договор.Номер Get end)

                // *** End programmer edit section *** (Договор.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Договор.Номер Set start)

                // *** End programmer edit section *** (Договор.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (Договор.Номер Set end)

                // *** End programmer edit section *** (Договор.Номер Set end)
            }
        }
        
        /// <summary>
        /// Договор.
        /// </summary>
        // *** Start programmer edit section *** (Договор.ЗакупкаТМЦ CustomAttributes)

        // *** End programmer edit section *** (Договор.ЗакупкаТМЦ CustomAttributes)
        public virtual IIS.PMZ.ЗакупкаТМЦ ЗакупкаТМЦ
        {
            get
            {
                // *** Start programmer edit section *** (Договор.ЗакупкаТМЦ Get start)

                // *** End programmer edit section *** (Договор.ЗакупкаТМЦ Get start)
                IIS.PMZ.ЗакупкаТМЦ result = this.fЗакупкаТМЦ;
                // *** Start programmer edit section *** (Договор.ЗакупкаТМЦ Get end)

                // *** End programmer edit section *** (Договор.ЗакупкаТМЦ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Договор.ЗакупкаТМЦ Set start)

                // *** End programmer edit section *** (Договор.ЗакупкаТМЦ Set start)
                this.fЗакупкаТМЦ = value;
                // *** Start programmer edit section *** (Договор.ЗакупкаТМЦ Set end)

                // *** End programmer edit section *** (Договор.ЗакупкаТМЦ Set end)
            }
        }
        
        /// <summary>
        /// Договор.
        /// </summary>
        // *** Start programmer edit section *** (Договор.Платёж CustomAttributes)

        // *** End programmer edit section *** (Договор.Платёж CustomAttributes)
        public virtual IIS.PMZ.DetailArrayOfПлатёж Платёж
        {
            get
            {
                // *** Start programmer edit section *** (Договор.Платёж Get start)

                // *** End programmer edit section *** (Договор.Платёж Get start)
                if ((this.fПлатёж == null))
                {
                    this.fПлатёж = new IIS.PMZ.DetailArrayOfПлатёж(this);
                }
                IIS.PMZ.DetailArrayOfПлатёж result = this.fПлатёж;
                // *** Start programmer edit section *** (Договор.Платёж Get end)

                // *** End programmer edit section *** (Договор.Платёж Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Договор.Платёж Set start)

                // *** End programmer edit section *** (Договор.Платёж Set start)
                this.fПлатёж = value;
                // *** Start programmer edit section *** (Договор.Платёж Set end)

                // *** End programmer edit section *** (Договор.Платёж Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДоговорE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДоговорE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДоговорE", typeof(IIS.PMZ.Договор));
                }
            }
            
            /// <summary>
            /// "ДоговорL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДоговорL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДоговорL", typeof(IIS.PMZ.Договор));
                }
            }
        }
    }
}
