//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.PMZ
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Заявка участника торгов.
    /// </summary>
    // *** Start programmer edit section *** (ЗаявкаУчастникаТоргов CustomAttributes)

    // *** End programmer edit section *** (ЗаявкаУчастникаТоргов CustomAttributes)
    [AutoAltered()]
    [Caption("Заявка участника торгов")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаявкаУчастникаТорговE", new string[] {
            "НаименованиеУчастника as \'Наименование участника\'",
            "Цена as \'Цена\'"})]
    public class ЗаявкаУчастникаТоргов : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименованиеУчастника;
        
        private double fЦена;
        
        private IIS.PMZ.ЗаявкаНаТорги fЗаявкаНаТорги;
        
        // *** Start programmer edit section *** (ЗаявкаУчастникаТоргов CustomMembers)

        // *** End programmer edit section *** (ЗаявкаУчастникаТоргов CustomMembers)

        
        /// <summary>
        /// НаименованиеУчастника.
        /// </summary>
        // *** Start programmer edit section *** (ЗаявкаУчастникаТоргов.НаименованиеУчастника CustomAttributes)

        // *** End programmer edit section *** (ЗаявкаУчастникаТоргов.НаименованиеУчастника CustomAttributes)
        [StrLen(255)]
        public virtual string НаименованиеУчастника
        {
            get
            {
                // *** Start programmer edit section *** (ЗаявкаУчастникаТоргов.НаименованиеУчастника Get start)

                // *** End programmer edit section *** (ЗаявкаУчастникаТоргов.НаименованиеУчастника Get start)
                string result = this.fНаименованиеУчастника;
                // *** Start programmer edit section *** (ЗаявкаУчастникаТоргов.НаименованиеУчастника Get end)

                // *** End programmer edit section *** (ЗаявкаУчастникаТоргов.НаименованиеУчастника Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаявкаУчастникаТоргов.НаименованиеУчастника Set start)

                // *** End programmer edit section *** (ЗаявкаУчастникаТоргов.НаименованиеУчастника Set start)
                this.fНаименованиеУчастника = value;
                // *** Start programmer edit section *** (ЗаявкаУчастникаТоргов.НаименованиеУчастника Set end)

                // *** End programmer edit section *** (ЗаявкаУчастникаТоргов.НаименованиеУчастника Set end)
            }
        }
        
        /// <summary>
        /// Цена.
        /// </summary>
        // *** Start programmer edit section *** (ЗаявкаУчастникаТоргов.Цена CustomAttributes)

        // *** End programmer edit section *** (ЗаявкаУчастникаТоргов.Цена CustomAttributes)
        public virtual double Цена
        {
            get
            {
                // *** Start programmer edit section *** (ЗаявкаУчастникаТоргов.Цена Get start)

                // *** End programmer edit section *** (ЗаявкаУчастникаТоргов.Цена Get start)
                double result = this.fЦена;
                // *** Start programmer edit section *** (ЗаявкаУчастникаТоргов.Цена Get end)

                // *** End programmer edit section *** (ЗаявкаУчастникаТоргов.Цена Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаявкаУчастникаТоргов.Цена Set start)

                // *** End programmer edit section *** (ЗаявкаУчастникаТоргов.Цена Set start)
                this.fЦена = value;
                // *** Start programmer edit section *** (ЗаявкаУчастникаТоргов.Цена Set end)

                // *** End programmer edit section *** (ЗаявкаУчастникаТоргов.Цена Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.PMZ.ЗаявкаНаТорги.
        /// </summary>
        // *** Start programmer edit section *** (ЗаявкаУчастникаТоргов.ЗаявкаНаТорги CustomAttributes)

        // *** End programmer edit section *** (ЗаявкаУчастникаТоргов.ЗаявкаНаТорги CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual IIS.PMZ.ЗаявкаНаТорги ЗаявкаНаТорги
        {
            get
            {
                // *** Start programmer edit section *** (ЗаявкаУчастникаТоргов.ЗаявкаНаТорги Get start)

                // *** End programmer edit section *** (ЗаявкаУчастникаТоргов.ЗаявкаНаТорги Get start)
                IIS.PMZ.ЗаявкаНаТорги result = this.fЗаявкаНаТорги;
                // *** Start programmer edit section *** (ЗаявкаУчастникаТоргов.ЗаявкаНаТорги Get end)

                // *** End programmer edit section *** (ЗаявкаУчастникаТоргов.ЗаявкаНаТорги Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаявкаУчастникаТоргов.ЗаявкаНаТорги Set start)

                // *** End programmer edit section *** (ЗаявкаУчастникаТоргов.ЗаявкаНаТорги Set start)
                this.fЗаявкаНаТорги = value;
                // *** Start programmer edit section *** (ЗаявкаУчастникаТоргов.ЗаявкаНаТорги Set end)

                // *** End programmer edit section *** (ЗаявкаУчастникаТоргов.ЗаявкаНаТорги Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаявкаУчастникаТорговE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаявкаУчастникаТорговE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаявкаУчастникаТорговE", typeof(IIS.PMZ.ЗаявкаУчастникаТоргов));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ЗаявкаУчастникаТоргов.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfЗаявкаУчастникаТоргов CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfЗаявкаУчастникаТоргов CustomAttributes)
    public class DetailArrayOfЗаявкаУчастникаТоргов : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.PMZ.DetailArrayOfЗаявкаУчастникаТоргов members)

        // *** End programmer edit section *** (IIS.PMZ.DetailArrayOfЗаявкаУчастникаТоргов members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ЗаявкаУчастникаТоргов by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ЗаявкаУчастникаТоргов.
        /// </summary>
        public DetailArrayOfЗаявкаУчастникаТоргов(IIS.PMZ.ЗаявкаНаТорги fЗаявкаНаТорги) : 
                base(typeof(ЗаявкаУчастникаТоргов), ((ICSSoft.STORMNET.DataObject)(fЗаявкаНаТорги)))
        {
        }
        
        public IIS.PMZ.ЗаявкаУчастникаТоргов this[int index]
        {
            get
            {
                return ((IIS.PMZ.ЗаявкаУчастникаТоргов)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.PMZ.ЗаявкаУчастникаТоргов dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
