//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.PMZ
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Заявка на торги.
    /// </summary>
    // *** Start programmer edit section *** (ЗаявкаНаТорги CustomAttributes)

    // *** End programmer edit section *** (ЗаявкаНаТорги CustomAttributes)
    [AutoAltered()]
    [Caption("Заявка на торги")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаявкаНаТоргиE", new string[] {
            "Дата as \'Дата\'",
            "Площадка as \'Площадка\'",
            "Договор as \'Договор\'",
            "Договор.Номер as \'Номер\'"})]
    [AssociatedDetailViewAttribute("ЗаявкаНаТоргиE", "ЗаявкаУчастникаТоргов", "ЗаявкаУчастникаТорговE", true, "", "Заявка участника торгов", true, new string[] {
            ""})]
    [View("ЗаявкаНаТоргиL", new string[] {
            "Дата as \'Дата\'",
            "Площадка as \'Площадка\'",
            "Договор.Номер as \'Номер\'"})]
    public class ЗаявкаНаТорги : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private string fПлощадка;
        
        private IIS.PMZ.Договор fДоговор;
        
        private IIS.PMZ.DetailArrayOfЗаявкаУчастникаТоргов fЗаявкаУчастникаТоргов;
        
        // *** Start programmer edit section *** (ЗаявкаНаТорги CustomMembers)

        // *** End programmer edit section *** (ЗаявкаНаТорги CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ЗаявкаНаТорги.Дата CustomAttributes)

        // *** End programmer edit section *** (ЗаявкаНаТорги.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ЗаявкаНаТорги.Дата Get start)

                // *** End programmer edit section *** (ЗаявкаНаТорги.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ЗаявкаНаТорги.Дата Get end)

                // *** End programmer edit section *** (ЗаявкаНаТорги.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаявкаНаТорги.Дата Set start)

                // *** End programmer edit section *** (ЗаявкаНаТорги.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ЗаявкаНаТорги.Дата Set end)

                // *** End programmer edit section *** (ЗаявкаНаТорги.Дата Set end)
            }
        }
        
        /// <summary>
        /// Площадка.
        /// </summary>
        // *** Start programmer edit section *** (ЗаявкаНаТорги.Площадка CustomAttributes)

        // *** End programmer edit section *** (ЗаявкаНаТорги.Площадка CustomAttributes)
        [StrLen(255)]
        public virtual string Площадка
        {
            get
            {
                // *** Start programmer edit section *** (ЗаявкаНаТорги.Площадка Get start)

                // *** End programmer edit section *** (ЗаявкаНаТорги.Площадка Get start)
                string result = this.fПлощадка;
                // *** Start programmer edit section *** (ЗаявкаНаТорги.Площадка Get end)

                // *** End programmer edit section *** (ЗаявкаНаТорги.Площадка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаявкаНаТорги.Площадка Set start)

                // *** End programmer edit section *** (ЗаявкаНаТорги.Площадка Set start)
                this.fПлощадка = value;
                // *** Start programmer edit section *** (ЗаявкаНаТорги.Площадка Set end)

                // *** End programmer edit section *** (ЗаявкаНаТорги.Площадка Set end)
            }
        }
        
        /// <summary>
        /// Заявка на торги.
        /// </summary>
        // *** Start programmer edit section *** (ЗаявкаНаТорги.Договор CustomAttributes)

        // *** End programmer edit section *** (ЗаявкаНаТорги.Договор CustomAttributes)
        public virtual IIS.PMZ.Договор Договор
        {
            get
            {
                // *** Start programmer edit section *** (ЗаявкаНаТорги.Договор Get start)

                // *** End programmer edit section *** (ЗаявкаНаТорги.Договор Get start)
                IIS.PMZ.Договор result = this.fДоговор;
                // *** Start programmer edit section *** (ЗаявкаНаТорги.Договор Get end)

                // *** End programmer edit section *** (ЗаявкаНаТорги.Договор Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаявкаНаТорги.Договор Set start)

                // *** End programmer edit section *** (ЗаявкаНаТорги.Договор Set start)
                this.fДоговор = value;
                // *** Start programmer edit section *** (ЗаявкаНаТорги.Договор Set end)

                // *** End programmer edit section *** (ЗаявкаНаТорги.Договор Set end)
            }
        }
        
        /// <summary>
        /// Заявка на торги.
        /// </summary>
        // *** Start programmer edit section *** (ЗаявкаНаТорги.ЗаявкаУчастникаТоргов CustomAttributes)

        // *** End programmer edit section *** (ЗаявкаНаТорги.ЗаявкаУчастникаТоргов CustomAttributes)
        public virtual IIS.PMZ.DetailArrayOfЗаявкаУчастникаТоргов ЗаявкаУчастникаТоргов
        {
            get
            {
                // *** Start programmer edit section *** (ЗаявкаНаТорги.ЗаявкаУчастникаТоргов Get start)

                // *** End programmer edit section *** (ЗаявкаНаТорги.ЗаявкаУчастникаТоргов Get start)
                if ((this.fЗаявкаУчастникаТоргов == null))
                {
                    this.fЗаявкаУчастникаТоргов = new IIS.PMZ.DetailArrayOfЗаявкаУчастникаТоргов(this);
                }
                IIS.PMZ.DetailArrayOfЗаявкаУчастникаТоргов result = this.fЗаявкаУчастникаТоргов;
                // *** Start programmer edit section *** (ЗаявкаНаТорги.ЗаявкаУчастникаТоргов Get end)

                // *** End programmer edit section *** (ЗаявкаНаТорги.ЗаявкаУчастникаТоргов Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаявкаНаТорги.ЗаявкаУчастникаТоргов Set start)

                // *** End programmer edit section *** (ЗаявкаНаТорги.ЗаявкаУчастникаТоргов Set start)
                this.fЗаявкаУчастникаТоргов = value;
                // *** Start programmer edit section *** (ЗаявкаНаТорги.ЗаявкаУчастникаТоргов Set end)

                // *** End programmer edit section *** (ЗаявкаНаТорги.ЗаявкаУчастникаТоргов Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаявкаНаТоргиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаявкаНаТоргиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаявкаНаТоргиE", typeof(IIS.PMZ.ЗаявкаНаТорги));
                }
            }
            
            /// <summary>
            /// "ЗаявкаНаТоргиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаявкаНаТоргиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаявкаНаТоргиL", typeof(IIS.PMZ.ЗаявкаНаТорги));
                }
            }
        }
    }
}
