//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.PMZ
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Закупка ТМЦ.
    /// </summary>
    // *** Start programmer edit section *** (ЗакупкаТМЦ CustomAttributes)

    // *** End programmer edit section *** (ЗакупкаТМЦ CustomAttributes)
    [AutoAltered()]
    [Caption("Закупка ТМЦ")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗакупкаТМЦE", new string[] {
            "СтартоваяЦена as \'Стартовая цена\'",
            "УсловияПоставкиИОплаты as \'Условия поставки и оплаты\'",
            "ТМЦ as \'ТМЦ\'",
            "ТМЦ.Наименование as \'Наименование\'"})]
    [View("ЗакупкаТМЦL", new string[] {
            "СтартоваяЦена as \'Стартовая цена\'",
            "УсловияПоставкиИОплаты as \'Условия поставки и оплаты\'",
            "ТМЦ.Наименование as \'Наименование\'"})]
    public class ЗакупкаТМЦ : ICSSoft.STORMNET.DataObject
    {
        
        private ICSSoft.STORMNET.UserDataTypes.NullableDecimal fСтартоваяЦена;
        
        private IIS.PMZ.tУсловияПоставкиИОплаты fУсловияПоставкиИОплаты;
        
        private IIS.PMZ.ТМЦ fТМЦ;
        
        // *** Start programmer edit section *** (ЗакупкаТМЦ CustomMembers)

        // *** End programmer edit section *** (ЗакупкаТМЦ CustomMembers)

        
        /// <summary>
        /// СтартоваяЦена.
        /// </summary>
        // *** Start programmer edit section *** (ЗакупкаТМЦ.СтартоваяЦена CustomAttributes)

        // *** End programmer edit section *** (ЗакупкаТМЦ.СтартоваяЦена CustomAttributes)
        [NotNull()]
        public virtual ICSSoft.STORMNET.UserDataTypes.NullableDecimal СтартоваяЦена
        {
            get
            {
                // *** Start programmer edit section *** (ЗакупкаТМЦ.СтартоваяЦена Get start)

                // *** End programmer edit section *** (ЗакупкаТМЦ.СтартоваяЦена Get start)
                ICSSoft.STORMNET.UserDataTypes.NullableDecimal result = this.fСтартоваяЦена;
                // *** Start programmer edit section *** (ЗакупкаТМЦ.СтартоваяЦена Get end)

                // *** End programmer edit section *** (ЗакупкаТМЦ.СтартоваяЦена Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗакупкаТМЦ.СтартоваяЦена Set start)

                // *** End programmer edit section *** (ЗакупкаТМЦ.СтартоваяЦена Set start)
                this.fСтартоваяЦена = value;
                // *** Start programmer edit section *** (ЗакупкаТМЦ.СтартоваяЦена Set end)

                // *** End programmer edit section *** (ЗакупкаТМЦ.СтартоваяЦена Set end)
            }
        }
        
        /// <summary>
        /// УсловияПоставкиИОплаты.
        /// </summary>
        // *** Start programmer edit section *** (ЗакупкаТМЦ.УсловияПоставкиИОплаты CustomAttributes)

        // *** End programmer edit section *** (ЗакупкаТМЦ.УсловияПоставкиИОплаты CustomAttributes)
        public virtual IIS.PMZ.tУсловияПоставкиИОплаты УсловияПоставкиИОплаты
        {
            get
            {
                // *** Start programmer edit section *** (ЗакупкаТМЦ.УсловияПоставкиИОплаты Get start)

                // *** End programmer edit section *** (ЗакупкаТМЦ.УсловияПоставкиИОплаты Get start)
                IIS.PMZ.tУсловияПоставкиИОплаты result = this.fУсловияПоставкиИОплаты;
                // *** Start programmer edit section *** (ЗакупкаТМЦ.УсловияПоставкиИОплаты Get end)

                // *** End programmer edit section *** (ЗакупкаТМЦ.УсловияПоставкиИОплаты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗакупкаТМЦ.УсловияПоставкиИОплаты Set start)

                // *** End programmer edit section *** (ЗакупкаТМЦ.УсловияПоставкиИОплаты Set start)
                this.fУсловияПоставкиИОплаты = value;
                // *** Start programmer edit section *** (ЗакупкаТМЦ.УсловияПоставкиИОплаты Set end)

                // *** End programmer edit section *** (ЗакупкаТМЦ.УсловияПоставкиИОплаты Set end)
            }
        }
        
        /// <summary>
        /// Закупка ТМЦ.
        /// </summary>
        // *** Start programmer edit section *** (ЗакупкаТМЦ.ТМЦ CustomAttributes)

        // *** End programmer edit section *** (ЗакупкаТМЦ.ТМЦ CustomAttributes)
        public virtual IIS.PMZ.ТМЦ ТМЦ
        {
            get
            {
                // *** Start programmer edit section *** (ЗакупкаТМЦ.ТМЦ Get start)

                // *** End programmer edit section *** (ЗакупкаТМЦ.ТМЦ Get start)
                IIS.PMZ.ТМЦ result = this.fТМЦ;
                // *** Start programmer edit section *** (ЗакупкаТМЦ.ТМЦ Get end)

                // *** End programmer edit section *** (ЗакупкаТМЦ.ТМЦ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗакупкаТМЦ.ТМЦ Set start)

                // *** End programmer edit section *** (ЗакупкаТМЦ.ТМЦ Set start)
                this.fТМЦ = value;
                // *** Start programmer edit section *** (ЗакупкаТМЦ.ТМЦ Set end)

                // *** End programmer edit section *** (ЗакупкаТМЦ.ТМЦ Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗакупкаТМЦE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗакупкаТМЦE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗакупкаТМЦE", typeof(IIS.PMZ.ЗакупкаТМЦ));
                }
            }
            
            /// <summary>
            /// "ЗакупкаТМЦL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗакупкаТМЦL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗакупкаТМЦL", typeof(IIS.PMZ.ЗакупкаТМЦ));
                }
            }
        }
    }
}
