//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.PMZ
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Отдел.
    /// </summary>
    // *** Start programmer edit section *** (Отдел CustomAttributes)

    // *** End programmer edit section *** (Отдел CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОтделE", new string[] {
            "Наименование as \'Наименование\'"})]
    [View("ОтделL", new string[] {
            "Наименование as \'Наименование\'"})]
    public class Отдел : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        // *** Start programmer edit section *** (Отдел CustomMembers)

        // *** End programmer edit section *** (Отдел CustomMembers)

        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Отдел.Наименование CustomAttributes)

        // *** End programmer edit section *** (Отдел.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Отдел.Наименование Get start)

                // *** End programmer edit section *** (Отдел.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Отдел.Наименование Get end)

                // *** End programmer edit section *** (Отдел.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Отдел.Наименование Set start)

                // *** End programmer edit section *** (Отдел.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Отдел.Наименование Set end)

                // *** End programmer edit section *** (Отдел.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОтделE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтделE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтделE", typeof(IIS.PMZ.Отдел));
                }
            }
            
            /// <summary>
            /// "ОтделL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтделL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтделL", typeof(IIS.PMZ.Отдел));
                }
            }
        }
    }
}
