//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.PMZ
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Платёж.
    /// </summary>
    // *** Start programmer edit section *** (Платёж CustomAttributes)

    // *** End programmer edit section *** (Платёж CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПлатёжE", new string[] {
            "Дата as \'Дата\'"})]
    public class Платёж : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private IIS.PMZ.Договор fДоговор;
        
        // *** Start programmer edit section *** (Платёж CustomMembers)

        // *** End programmer edit section *** (Платёж CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (Платёж.Дата CustomAttributes)

        // *** End programmer edit section *** (Платёж.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (Платёж.Дата Get start)

                // *** End programmer edit section *** (Платёж.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (Платёж.Дата Get end)

                // *** End programmer edit section *** (Платёж.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Платёж.Дата Set start)

                // *** End programmer edit section *** (Платёж.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (Платёж.Дата Set end)

                // *** End programmer edit section *** (Платёж.Дата Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.PMZ.Договор.
        /// </summary>
        // *** Start programmer edit section *** (Платёж.Договор CustomAttributes)

        // *** End programmer edit section *** (Платёж.Договор CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual IIS.PMZ.Договор Договор
        {
            get
            {
                // *** Start programmer edit section *** (Платёж.Договор Get start)

                // *** End programmer edit section *** (Платёж.Договор Get start)
                IIS.PMZ.Договор result = this.fДоговор;
                // *** Start programmer edit section *** (Платёж.Договор Get end)

                // *** End programmer edit section *** (Платёж.Договор Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Платёж.Договор Set start)

                // *** End programmer edit section *** (Платёж.Договор Set start)
                this.fДоговор = value;
                // *** Start programmer edit section *** (Платёж.Договор Set end)

                // *** End programmer edit section *** (Платёж.Договор Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПлатёжE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПлатёжE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПлатёжE", typeof(IIS.PMZ.Платёж));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Платёж.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfПлатёж CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfПлатёж CustomAttributes)
    public class DetailArrayOfПлатёж : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.PMZ.DetailArrayOfПлатёж members)

        // *** End programmer edit section *** (IIS.PMZ.DetailArrayOfПлатёж members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Платёж by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Платёж.
        /// </summary>
        public DetailArrayOfПлатёж(IIS.PMZ.Договор fДоговор) : 
                base(typeof(Платёж), ((ICSSoft.STORMNET.DataObject)(fДоговор)))
        {
        }
        
        public IIS.PMZ.Платёж this[int index]
        {
            get
            {
                return ((IIS.PMZ.Платёж)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.PMZ.Платёж dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
