//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.PMZ
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Потребность ВТМЦ.
    /// </summary>
    // *** Start programmer edit section *** (ПотребностьВТМЦ CustomAttributes)

    // *** End programmer edit section *** (ПотребностьВТМЦ CustomAttributes)
    [AutoAltered()]
    [Caption("Потребность ВТМЦ")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПотребностьВТМЦE", new string[] {
            "ВидЗакупки as \'Вид закупки\'",
            "ТМЦ as \'ТМЦ\'",
            "ТМЦ.Наименование as \'Наименование\'",
            "Отдел as \'Отдел\'",
            "Отдел.Наименование as \'Наименование\'",
            "ЗакупкаТМЦ as \'Закупка ТМЦ\'",
            "ЗакупкаТМЦ.СтартоваяЦена as \'Стартовая цена\'"})]
    [View("ПотребностьВТМЦL", new string[] {
            "ВидЗакупки as \'Вид закупки\'",
            "ТМЦ.Наименование as \'Наименование\'",
            "Отдел.Наименование as \'Наименование\'",
            "ЗакупкаТМЦ.СтартоваяЦена as \'Стартовая цена\'"})]
    public class ПотребностьВТМЦ : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.PMZ.tВидЗакупки fВидЗакупки;
        
        private IIS.PMZ.ТМЦ fТМЦ;
        
        private IIS.PMZ.Отдел fОтдел;
        
        private IIS.PMZ.ЗакупкаТМЦ fЗакупкаТМЦ;
        
        // *** Start programmer edit section *** (ПотребностьВТМЦ CustomMembers)

        // *** End programmer edit section *** (ПотребностьВТМЦ CustomMembers)

        
        /// <summary>
        /// ВидЗакупки.
        /// </summary>
        // *** Start programmer edit section *** (ПотребностьВТМЦ.ВидЗакупки CustomAttributes)

        // *** End programmer edit section *** (ПотребностьВТМЦ.ВидЗакупки CustomAttributes)
        public virtual IIS.PMZ.tВидЗакупки ВидЗакупки
        {
            get
            {
                // *** Start programmer edit section *** (ПотребностьВТМЦ.ВидЗакупки Get start)

                // *** End programmer edit section *** (ПотребностьВТМЦ.ВидЗакупки Get start)
                IIS.PMZ.tВидЗакупки result = this.fВидЗакупки;
                // *** Start programmer edit section *** (ПотребностьВТМЦ.ВидЗакупки Get end)

                // *** End programmer edit section *** (ПотребностьВТМЦ.ВидЗакупки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПотребностьВТМЦ.ВидЗакупки Set start)

                // *** End programmer edit section *** (ПотребностьВТМЦ.ВидЗакупки Set start)
                this.fВидЗакупки = value;
                // *** Start programmer edit section *** (ПотребностьВТМЦ.ВидЗакупки Set end)

                // *** End programmer edit section *** (ПотребностьВТМЦ.ВидЗакупки Set end)
            }
        }
        
        /// <summary>
        /// Потребность ВТМЦ.
        /// </summary>
        // *** Start programmer edit section *** (ПотребностьВТМЦ.ТМЦ CustomAttributes)

        // *** End programmer edit section *** (ПотребностьВТМЦ.ТМЦ CustomAttributes)
        public virtual IIS.PMZ.ТМЦ ТМЦ
        {
            get
            {
                // *** Start programmer edit section *** (ПотребностьВТМЦ.ТМЦ Get start)

                // *** End programmer edit section *** (ПотребностьВТМЦ.ТМЦ Get start)
                IIS.PMZ.ТМЦ result = this.fТМЦ;
                // *** Start programmer edit section *** (ПотребностьВТМЦ.ТМЦ Get end)

                // *** End programmer edit section *** (ПотребностьВТМЦ.ТМЦ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПотребностьВТМЦ.ТМЦ Set start)

                // *** End programmer edit section *** (ПотребностьВТМЦ.ТМЦ Set start)
                this.fТМЦ = value;
                // *** Start programmer edit section *** (ПотребностьВТМЦ.ТМЦ Set end)

                // *** End programmer edit section *** (ПотребностьВТМЦ.ТМЦ Set end)
            }
        }
        
        /// <summary>
        /// Потребность ВТМЦ.
        /// </summary>
        // *** Start programmer edit section *** (ПотребностьВТМЦ.Отдел CustomAttributes)

        // *** End programmer edit section *** (ПотребностьВТМЦ.Отдел CustomAttributes)
        public virtual IIS.PMZ.Отдел Отдел
        {
            get
            {
                // *** Start programmer edit section *** (ПотребностьВТМЦ.Отдел Get start)

                // *** End programmer edit section *** (ПотребностьВТМЦ.Отдел Get start)
                IIS.PMZ.Отдел result = this.fОтдел;
                // *** Start programmer edit section *** (ПотребностьВТМЦ.Отдел Get end)

                // *** End programmer edit section *** (ПотребностьВТМЦ.Отдел Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПотребностьВТМЦ.Отдел Set start)

                // *** End programmer edit section *** (ПотребностьВТМЦ.Отдел Set start)
                this.fОтдел = value;
                // *** Start programmer edit section *** (ПотребностьВТМЦ.Отдел Set end)

                // *** End programmer edit section *** (ПотребностьВТМЦ.Отдел Set end)
            }
        }
        
        /// <summary>
        /// Потребность ВТМЦ.
        /// </summary>
        // *** Start programmer edit section *** (ПотребностьВТМЦ.ЗакупкаТМЦ CustomAttributes)

        // *** End programmer edit section *** (ПотребностьВТМЦ.ЗакупкаТМЦ CustomAttributes)
        public virtual IIS.PMZ.ЗакупкаТМЦ ЗакупкаТМЦ
        {
            get
            {
                // *** Start programmer edit section *** (ПотребностьВТМЦ.ЗакупкаТМЦ Get start)

                // *** End programmer edit section *** (ПотребностьВТМЦ.ЗакупкаТМЦ Get start)
                IIS.PMZ.ЗакупкаТМЦ result = this.fЗакупкаТМЦ;
                // *** Start programmer edit section *** (ПотребностьВТМЦ.ЗакупкаТМЦ Get end)

                // *** End programmer edit section *** (ПотребностьВТМЦ.ЗакупкаТМЦ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПотребностьВТМЦ.ЗакупкаТМЦ Set start)

                // *** End programmer edit section *** (ПотребностьВТМЦ.ЗакупкаТМЦ Set start)
                this.fЗакупкаТМЦ = value;
                // *** Start programmer edit section *** (ПотребностьВТМЦ.ЗакупкаТМЦ Set end)

                // *** End programmer edit section *** (ПотребностьВТМЦ.ЗакупкаТМЦ Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПотребностьВТМЦE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПотребностьВТМЦE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПотребностьВТМЦE", typeof(IIS.PMZ.ПотребностьВТМЦ));
                }
            }
            
            /// <summary>
            /// "ПотребностьВТМЦL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПотребностьВТМЦL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПотребностьВТМЦL", typeof(IIS.PMZ.ПотребностьВТМЦ));
                }
            }
        }
    }
}
