//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.PMZ
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ТМЦ.
    /// </summary>
    // *** Start programmer edit section *** (ТМЦ CustomAttributes)

    // *** End programmer edit section *** (ТМЦ CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТМЦE", new string[] {
            "Наименование as \'Наименование\'"})]
    [View("ТМЦL", new string[] {
            "Наименование as \'Наименование\'"})]
    public class ТМЦ : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        // *** Start programmer edit section *** (ТМЦ CustomMembers)

        // *** End programmer edit section *** (ТМЦ CustomMembers)

        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (ТМЦ.Наименование CustomAttributes)

        // *** End programmer edit section *** (ТМЦ.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (ТМЦ.Наименование Get start)

                // *** End programmer edit section *** (ТМЦ.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (ТМЦ.Наименование Get end)

                // *** End programmer edit section *** (ТМЦ.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТМЦ.Наименование Set start)

                // *** End programmer edit section *** (ТМЦ.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (ТМЦ.Наименование Set end)

                // *** End programmer edit section *** (ТМЦ.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТМЦE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТМЦE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТМЦE", typeof(IIS.PMZ.ТМЦ));
                }
            }
            
            /// <summary>
            /// "ТМЦL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТМЦL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТМЦL", typeof(IIS.PMZ.ТМЦ));
                }
            }
        }
    }
}
